id: ch.fhir.ig.ch-ems
canonical: http://fhir.ch/ig/ch-ems
name: CH_EMS
title: "CH EMS (R4)"
description: Implementation Guide for the Emergency Medical Service protocol
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2025-01-08
version: 2.1.0-ci-build
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

publisher:
  name: IVR Interverband für Rettungswesen
contact:
  - name: IVR Interverband für Rettungswesen
    telecom:
      - system: url
        value: https://www.ivr-ias.ch/

dependencies:
  ch.fhir.ig.ch-core: 5.0.0

parameters:
  special-url: 
    - urn:oid:2.16.756.5.30.1.143.5.1 # IVR Code System
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true    

pages:
  index.md:
    title: Home
  index-german.md:
    title: Home (DE)
  index-french.md:
    title: Home (FR)     
  usecase-german.md:
    title: Anwendungsfälle
  usecase-french.md:
    title: Cas d’application  
  document.md:
    title: Emergency Medical Service protocol 
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog
