id: ch.fhir.ig.ch-ems
canonical: http://fhir.ch/ig/ch-ems
name: CH_EMS
title: "CH EMS (R4)"
description: Implementation Guide for the Emergency Medical Service protocol
status: active
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2021-12-21
version: 1.9.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: CI Build

publisher:
  name: IVR Interverband für Rettungswesen
contact:
  name: IVR Interverband für Rettungswesen
  telecom:
    system: url
    value: https://www.ivr-ias.ch/

dependencies:
  ch.fhir.ig.ch-core: 1.0.0 # TBD next release -> update to new version  

parameters:
  special-url: urn:oid:2.16.756.5.30.1.143.5.1 # IVR Code System

pages:
  index.md:
    title: Home
  index-german.md:
    title: Home (DE)
  index-french.md:
    title: Home (FR)     
  usecase-german.md:
    title: Anwendungsfälle
  usecase-french.md:
    title: Cas d’application  
  document.md:
    title: Emergency Medical Service protocol 
  profiles.html:
    title: Profiles
  extensions.html:
    title: Extensions
  terminology.html:
    title: Terminology

