id: ch.fhir.ig.ch-ems
canonical: http://fhir.ch/ig/ch-ems
name: CH_EMS
title: "CH EMS (R4)"
description: Implementation Guide for the Emergency Medical Service protocol
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH
date: 2025-01-08 # TODO before publication: check status and version of value sets
version: 2.1.0-ci-build
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use

publisher:
  name: IVR Interverband für Rettungswesen
contact:
  - name: IVR Interverband für Rettungswesen
    telecom:
      - system: url
        value: https://www.ivr-ias.ch/

dependencies:
  ch.fhir.ig.ch-core: 5.0.0
  ch.fhir.ig.ch-term: 3.2.x
  hl7.terminology.r4: 
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    version: 6.5.0 

pages:
  index.md:
    title: Home
  index-german.md:
    title: Home (DE)
  index-french.md:
    title: Home (FR)     
  usecase-german.md:
    title: Anwendungsfälle
  usecase-french.md:
    title: Cas d’application  
  document.md:
    title: Emergency Medical Service protocol 
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog

menu:
  Home:
    English: index.html
    German: index-german.html
    French: index-french.html
  Use Case:
    German: usecase-german.html
    French: usecase-french.html
  Document: document.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html

# For parameters defined by core FHIR see: 
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG  see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true    
  path-expansion-params: '../../expansion-params.json' # for using SNOMED CT Swiss Extension  
  pin-canonicals: pin-multiples
  no-narrative: 
  - Bundle/*
  - Composition/*
  - Coverage/*
  - Encounter/*
  - Location/*
  - Observation/*
  - Organization/*
  - Patient/*
  - Practitioner/*
  - PractitionerRole/*
  - Procedure/*
  - ServiceRequest/*

instanceOptions:  
  setMetaProfile: never

