Instance: EmsHandover2Fhir
InstanceOf: ConceptMap
Title: "EMS Handover to FHIR Mapping"
Description: "This map shows how the handover section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsHandover2Fhir"
* title = "EMS Handover to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsHandover2Fhir"> </a><a name="hcEmsHandover2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover">EMSProtocol.handover</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.section:handover">Composition.section:handover</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-statuspriority.html">CH EMS Observation: Status Priority</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.priority">EMSProtocol.handover.priority</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-statuspriority-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-conditionchange.html">CH EMS Observation: Condition Change</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.conditionChange">EMSProtocol.handover.conditionChange</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-conditionchange-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 4 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-naca.html">CH EMS Observation: NACA</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.injurySeverity">EMSProtocol.handover.injurySeverity</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-naca-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 5 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-gcs.html">CH EMS Observation: GCS</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.total">EMSProtocol.handover.gcs.total</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.eyeOpening.score">EMSProtocol.handover.gcs.eyeOpening.score</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:eyeOpening.value[x].coding.extension:itemWeight">Observation.component:eyeOpening.value[x].coding.extension:itemWeight</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.eyeOpening.description">EMSProtocol.handover.gcs.eyeOpening.description</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:eyeOpening.value[x]">Observation.component:eyeOpening.value[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.verbalResponse.score">EMSProtocol.handover.gcs.verbalResponse.score</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:verbal.value[x].coding.extension:itemWeight">Observation.component:verbal.value[x].coding.extension:itemWeight</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.verbalResponse.description">EMSProtocol.handover.gcs.verbalResponse.description</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:verbal.value[x]">Observation.component:verbal.value[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.motorResponse.score">EMSProtocol.handover.gcs.motorResponse.score</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:motor.value[x].coding.extension:itemWeight">Observation.component:motor.value[x].coding.extension:itemWeight</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.gcs.motorResponse.description">EMSProtocol.handover.gcs.motorResponse.description</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-gcs-definitions.html#Observation.component:motor.value[x]">Observation.component:motor.value[x]</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 6 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-organization.html">CH EMS Organization</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.recipient.organisation">EMSProtocol.handover.recipient.organisation</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-organization-definitions.html#Organization">Organization</a></td><td>0..*</td><td>todo</td></tr></table><hr/><p><b>Group 7 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-practitioner.html">CH EMS Practitioner</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.handover.recipient.practitioner">EMSProtocol.handover.recipient.practitioner</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner">Practitioner</a></td><td>0..*</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.handover
* group[=].element[=].target.code = #Composition.section:handover
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-statuspriority" 
* group[=].element[0].code = #EMSProtocol.handover.priority
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-conditionchange" 
* group[=].element[0].code = #EMSProtocol.handover.conditionChange
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-naca" 
* group[=].element[0].code = #EMSProtocol.handover.injurySeverity
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-gcs" 
* group[=].element[0].code = #EMSProtocol.handover.gcs.total
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.eyeOpening.score
* group[=].element[=].target.code = #Observation.component:eyeOpening.value[x].coding.extension:itemWeight
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.eyeOpening.description
* group[=].element[=].target.code = #Observation.component:eyeOpening.value[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.verbalResponse.score
* group[=].element[=].target.code = #Observation.component:verbal.value[x].coding.extension:itemWeight
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.verbalResponse.description
* group[=].element[=].target.code = #Observation.component:verbal.value[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.motorResponse.score
* group[=].element[=].target.code = #Observation.component:motor.value[x].coding.extension:itemWeight
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.handover.gcs.motorResponse.description
* group[=].element[=].target.code = #Observation.component:motor.value[x]
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-organization" 
* group[=].element[0].code = #EMSProtocol.handover.recipient.organisation
* group[=].element[=].target.code = #Organization
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-practitioner" 
* group[=].element[0].code = #EMSProtocol.handover.recipient.practitioner
* group[=].element[=].target.code = #Practitioner
* group[=].element[=].target.equivalence = #equivalent