Instance: EmsPatient2Fhir
InstanceOf: ConceptMap
Title: "EMS Patient to FHIR Mapping"
Description: "This map shows how the patient section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsPatient2Fhir"
* title = "EMS Patient to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsPatient2Fhir"> </a><a name="hcEmsPatient2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient">EMSProtocol.patient</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.subject">Composition.subject</a></td><td>1..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-patient.html">CH EMS Patient</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.name">EMSProtocol.patient.name</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.name">Patient.name</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.name.firstName">EMSProtocol.patient.name.firstName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.name.given">Patient.name.given</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.name.lastName">EMSProtocol.patient.name.lastName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.name.family">Patient.name.family</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.placeOfOrigin">EMSProtocol.patient.placeOfOrigin</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.extension:placeOfOrigin">Patient.extension:placeOfOrigin</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.citizenship">EMSProtocol.patient.citizenship</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.extension:citizenship">Patient.extension:citizenship</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.birthDate">EMSProtocol.patient.birthDate</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.birthDate">Patient.birthDate</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.gender">EMSProtocol.patient.gender</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.gender">Patient.gender</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.insuranceCardNumber">EMSProtocol.patient.insuranceCardNumber</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.identifier:AHVN13">Patient.identifier:AHVN13</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.oasiNumber">EMSProtocol.patient.oasiNumber</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.identifier:AHVN13">Patient.identifier:AHVN13</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.plsId">EMSProtocol.patient.plsId</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.identifier:LocalPid">Patient.identifier:LocalPid</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.identification">EMSProtocol.patient.identification</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.extension:identification">Patient.extension:identification</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.identification.medium">EMSProtocol.patient.identification.medium</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.extension:identification.extension:medium">Patient.extension:identification.extension:medium</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.identification.source">EMSProtocol.patient.identification.source</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.extension:identification.extension:source">Patient.extension:identification.extension:source</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.address">EMSProtocol.patient.address</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.address">Patient.address</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.address.street">EMSProtocol.patient.address.street</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.address.line">Patient.address.line</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.address.zipCode">EMSProtocol.patient.address.zipCode</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.address.postalCode">Patient.address.postalCode</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.address.city">EMSProtocol.patient.address.city</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-patient-definitions.html#Patient.address.city">Patient.address.city</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-servicerequest.html">CH EMS ServiceRequest</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.insurance">EMSProtocol.patient.insurance</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-servicerequest-definitions.html#ServiceRequest.insurance">ServiceRequest.insurance</a></td><td>0..*</td><td>todo</td></tr></table><hr/><p><b>Group 4 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-coverage.html">CH EMS Coverage</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.insurance">EMSProtocol.patient.insurance</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-coverage-definitions.html#Coverage.payor">Coverage.payor</a></td><td>1..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.patient.insuranceCardNumber">EMSProtocol.patient.insuranceCardNumber</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-coverage-definitions.html#Coverage.identifier:insuranceCardNumber">Coverage.identifier:insuranceCardNumber</a></td><td>0..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.patient
* group[=].element[=].target.code = #Composition.subject
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-patient"
* group[=].element[0].code = #EMSProtocol.patient.name
* group[=].element[=].target.code = #Patient.name
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.name.firstName
* group[=].element[=].target.code = #Patient.name.given
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.name.lastName
* group[=].element[=].target.code = #Patient.name.family
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.placeOfOrigin
* group[=].element[=].target.code = #Patient.extension:placeOfOrigin
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.citizenship
* group[=].element[=].target.code = #Patient.extension:citizenship
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.birthDate
* group[=].element[=].target.code = #Patient.birthDate
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.gender
* group[=].element[=].target.code = #Patient.gender
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.insuranceCardNumber
* group[=].element[=].target.code = #Patient.identifier:AHVN13
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.oasiNumber
* group[=].element[=].target.code = #Patient.identifier:AHVN13
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.plsId
* group[=].element[=].target.code = #Patient.identifier:LocalPid
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.identification
* group[=].element[=].target.code = #Patient.extension:identification
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.identification.medium
* group[=].element[=].target.code = #Patient.extension:identification.extension:medium
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.identification.source
* group[=].element[=].target.code = #Patient.extension:identification.extension:source
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.address
* group[=].element[=].target.code = #Patient.address
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.address.street
* group[=].element[=].target.code = #Patient.address.line
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.address.zipCode
* group[=].element[=].target.code = #Patient.address.postalCode
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.address.city
* group[=].element[=].target.code = #Patient.address.city
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-servicerequest"
* group[=].element[0].code = #EMSProtocol.patient.insurance
* group[=].element[=].target.code = #ServiceRequest.insurance
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-coverage"
* group[=].element[0].code = #EMSProtocol.patient.insurance
* group[=].element[=].target.code = #Coverage.payor
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.patient.insuranceCardNumber
* group[=].element[=].target.code = #Coverage.identifier:insuranceCardNumber
* group[=].element[=].target.equivalence = #equivalent
