Instance: EmsPretreatment2Fhir
InstanceOf: ConceptMap
Title: "EMS Pretreatment to FHIR Mapping"
Description: "This map shows how the pretreatment section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsPretreatment2Fhir"
* title = "EMS Pretreatment to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsPretreatment2Fhir"> </a><a name="hcEmsPretreatment2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.pretreatment">EMSProtocol.pretreatment</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.section:pretreatment">Composition.section:pretreatment</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure-pretreatment.html">CH EMS Procedure: Pretreatment</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.pretreatment.type">EMSProtocol.pretreatment.type</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-pretreatment-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.pretreatment.performer">EMSProtocol.pretreatment.performer</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-pretreatment-definitions.html#Procedure.extension:performer">Procedure.extension:performer</a></td><td>0..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.pretreatment
* group[=].element[=].target.code = #Composition.section:pretreatment
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure-pretreatment" // ?codesystem
* group[=].element[0].code = #EMSProtocol.pretreatment.type
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.pretreatment.performer
* group[=].element[=].target.code = #Procedure.extension:performer
* group[=].element[=].target.equivalence = #equivalent
