Instance: EmsAnamnesis2Fhir
InstanceOf: ConceptMap
Title: "EMS Anamnesis to FHIR Mapping"
Description: "This map shows how the anamnesis section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsAnamnesis2Fhir"
* title = "EMS Anamnesis to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsAnamnesis2Fhir"> </a><a name="hcEmsAnamnesis2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis">EMSProtocol.anamnesis</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.section:anamnesis">Composition.section:anamnesis</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-anamnesisevent.html">CH EMS Observation: Anamnesis Event</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.event">EMSProtocol.anamnesis.event</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesisevent-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.event.code">EMSProtocol.anamnesis.event.code</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesisevent-definitions.html#Observation.value[x].coding">Observation.value[x].coding</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.event.freeText">EMSProtocol.anamnesis.event.freeText</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesisevent-definitions.html#Observation.value[x].text">Observation.value[x].text</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-anamnesissymptom.html">CH EMS Observation: Anamnesis Symptom</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.symptom">EMSProtocol.anamnesis.symptom</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesissymptom-definitions.html#Observation.value[x]">Observation.value[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.symptom.code">EMSProtocol.anamnesis.symptom.code</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesissymptom-definitions.html#Observation.value[x].coding">Observation.value[x].coding</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.symptom.freeText">EMSProtocol.anamnesis.symptom.freeText</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-anamnesissymptom-definitions.html#Observation.value[x].text">Observation.value[x].text</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 4 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-allergyintolerance.html">CH EMS AllergyIntolerance</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.allergyIntolerance.type">EMSProtocol.anamnesis.allergyIntolerance.type</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-allergyintolerance-definitions.html#AllergyIntolerance.type">AllergyIntolerance.type</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.allergyIntolerance.code">EMSProtocol.anamnesis.allergyIntolerance.code</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-allergyintolerance-definitions.html#AllergyIntolerance.code">AllergyIntolerance.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 5 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-medicationstatement.html">CH EMS MedicationStatement</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.medication">EMSProtocol.anamnesis.medicationStatement.medication</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.medication[x]">MedicationStatement.medication[x]</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.dosePerUnit">EMSProtocol.anamnesis.medicationStatement.dosePerUnit</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.dosage.doseAndRate.dose[x]">MedicationStatement.dosage.doseAndRate.dose[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.dosage.scheme">EMSProtocol.anamnesis.medicationStatement.dosage.scheme</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.dosage.timing.repeat.when">MedicationStatement.dosage.timing.repeat.when</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.dosage.freeText">EMSProtocol.anamnesis.medicationStatement.dosage.freeText</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.dosage.patientInstruction">MedicationStatement.dosage.patientInstruction</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.asNeeded">EMSProtocol.anamnesis.medicationStatement.asNeeded</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.dosage.asNeeded[x]">MedicationStatement.dosage.asNeeded[x]</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.reason">EMSProtocol.anamnesis.medicationStatement.reason</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationstatement-definitions.html#MedicationStatement.reasonCode.text">MedicationStatement.reasonCode.text</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 6 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-medication.html">CH EMS Medication</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.medication.product.gtin">EMSProtocol.anamnesis.medicationStatement.medication.product.gtin</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.coding:GTIN">Medication.code.coding:GTIN</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.medication.product.atc">EMSProtocol.anamnesis.medicationStatement.medication.product.atc</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.coding:ATC">Medication.code.coding:ATC</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.medication.product.freeText">EMSProtocol.anamnesis.medicationStatement.medication.product.freeText</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.text">Medication.code.text</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.anamnesis.medicationStatement.medication.ingredient">EMSProtocol.anamnesis.medicationStatement.medication.ingredient</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.ingredient.item[x]">Medication.ingredient.item[x]</a></td><td>1..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.anamnesis
* group[=].element[=].target.code = #Composition.section:anamnesis
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-anamnesisevent" 
* group[=].element[0].code = #EMSProtocol.anamnesis.event
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.event.code
* group[=].element[=].target.code = #Observation.value[x].coding
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.event.freeText
* group[=].element[=].target.code = #Observation.value[x].text
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-anamnesissymptom" 
* group[=].element[0].code = #EMSProtocol.anamnesis.symptom
* group[=].element[=].target.code = #Observation.value[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.symptom.code
* group[=].element[=].target.code = #Observation.value[x].coding
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.symptom.freeText
* group[=].element[=].target.code = #Observation.value[x].text
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-allergyintolerance" 
* group[=].element[0].code = #EMSProtocol.anamnesis.allergyIntolerance.type
* group[=].element[=].target.code = #AllergyIntolerance.type
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.allergyIntolerance.code
* group[=].element[=].target.code = #AllergyIntolerance.code
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-medicationstatement" 
* group[=].element[0].code = #EMSProtocol.anamnesis.medicationStatement.medication
* group[=].element[=].target.code = #MedicationStatement.medication[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.dosePerUnit
* group[=].element[=].target.code = #MedicationStatement.dosage.doseAndRate.dose[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.dosage.scheme
* group[=].element[=].target.code = #MedicationStatement.dosage.timing.repeat.when
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.dosage.freeText
* group[=].element[=].target.code = #MedicationStatement.dosage.patientInstruction
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.asNeeded
* group[=].element[=].target.code = #MedicationStatement.dosage.asNeeded[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.reason
* group[=].element[=].target.code = #MedicationStatement.reasonCode.text
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-medication" 
* group[=].element[0].code = #EMSProtocol.anamnesis.medicationStatement.medication.product.gtin
* group[=].element[=].target.code = #Medication.code.coding:GTIN
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.medication.product.atc
* group[=].element[=].target.code = #Medication.code.coding:ATC
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.medication.product.freeText
* group[=].element[=].target.code = #Medication.code.text
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.anamnesis.medicationStatement.medication.ingredient
* group[=].element[=].target.code = #Medication.ingredient.item[x]
* group[=].element[=].target.equivalence = #equivalent



