Instance: EmsDiagnosis2Fhir
InstanceOf: ConceptMap
Title: "EMS Diagnosis to FHIR Mapping"
Description: "This map shows how the diagnosis section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsDiagnosis2Fhir"
* title = "EMS Diagnosis to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsDiagnosis2Fhir"> </a><a name="hcEmsDiagnosis2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis">EMSProtocol.diagnosis</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.section:diagnosis">Composition.section:diagnosis</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-observation-diagnosis.html">CH EMS Observation: Diagnosis</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.type">EMSProtocol.diagnosis.type</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-diagnosis-definitions.html#Observation.code">Observation.code</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author">EMSProtocol.diagnosis.author</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-diagnosis-definitions.html#Observation.performer">Observation.performer</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.icd10">EMSProtocol.diagnosis.icd10</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-observation-diagnosis-definitions.html#Observation.value[x].coding:icd10">Observation.value[x].coding:icd10</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-practitioner.html">CH EMS Practitioner</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author.name">EMSProtocol.diagnosis.author.name</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner.name">Practitioner.name</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author.name.firstName">EMSProtocol.diagnosis.author.name.firstName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner.name.given">Practitioner.name.given</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author.name.lastName">EMSProtocol.diagnosis.author.name.lastName</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner.name.family">Practitioner.name.family</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author.gln">EMSProtocol.diagnosis.author.gln</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner.identifier:GLN">Practitioner.identifier:GLN</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.diagnosis.author.formation">EMSProtocol.diagnosis.author.formation</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-practitioner-definitions.html#Practitioner.qualification.code">Practitioner.qualification.code</a></td><td>1..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.diagnosis
* group[=].element[=].target.code = #Composition.section:diagnosis
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-observation-diagnosis"
* group[=].element[0].code = #EMSProtocol.diagnosis.type
* group[=].element[=].target.code = #Observation.code
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.author
* group[=].element[=].target.code = #Observation.performer
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.icd10
* group[=].element[=].target.code = #Observation.value[x].coding:icd10
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-practitioner"
* group[=].element[0].code = #EMSProtocol.diagnosis.author.name
* group[=].element[=].target.code = #Practitioner.name
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.author.name.firstName
* group[=].element[=].target.code = #Practitioner.name.given
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.author.name.lastName
* group[=].element[=].target.code = #Practitioner.name.family
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.author.gln
* group[=].element[=].target.code = #Practitioner.identifier:GLN
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.diagnosis.author.formation
* group[=].element[=].target.code = #Practitioner.qualification.code
* group[=].element[=].target.equivalence = #equivalent
