Instance: EmsProcedures2Fhir
InstanceOf: ConceptMap
Title: "EMS Procedures to FHIR Mapping"
Description: "This map shows how the procedures section from the EMS Protocol is represented using FHIR."
Usage: #definition
* status = #active
* experimental = false
* name = "EmsProcedures2Fhir"
* title = "EMS Procedures to FHIR Mapping"

// Commented out to avoid CONCEPTMAP_VS_NOT_A_VS error: sourceUri/targetUri must point to a ValueSet, not a StructureDefinition. See https://github.com/hl7ch/ch-ems/issues/42
// * sourceUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
// * targetUri = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-document"

// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)
* text.status = #additional
* text.div = """
<div xmlns="http://www.w3.org/1999/xhtml"><a name="EmsProcedures2Fhir"> </a><a name="hcEmsProcedures2Fhir"> </a><p>Mapping from (not specified) to (not specified)</p><br/><p><b>Group 1 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-composition.html">CH EMS Composition</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures">EMSProtocol.procedures</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-composition-definitions.html#Composition.section:procedures">Composition.section:procedures</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 2 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-medicationadministration.html">CH EMS MedicationAdministration</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication">EMSProtocol.procedures.medicationAdministration.medication</a></td><td>1..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.medication[x]">MedicationAdministration.medication[x]</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.dose">EMSProtocol.procedures.medicationAdministration.dose</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.dosage.dose">MedicationAdministration.dosage.dose</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.timing.time">EMSProtocol.procedures.medicationAdministration.timing.time</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.effective[x]">MedicationAdministration.effective[x]</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.timing.period">EMSProtocol.procedures.medicationAdministration.timing.period</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.effective[x]">MedicationAdministration.effective[x]</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.routeOfAdministration">EMSProtocol.procedures.medicationAdministration.routeOfAdministration</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.dosage.route">MedicationAdministration.dosage.route</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.methodOfAdministration">EMSProtocol.procedures.medicationAdministration.methodOfAdministration</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.dosage.method">MedicationAdministration.dosage.method</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.reason">EMSProtocol.procedures.medicationAdministration.reason</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medicationadministration-definitions.html#MedicationAdministration.reasonCode.text">MedicationAdministration.reasonCode.text</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 3 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-medication.html">CH EMS Medication</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.product.gtin">EMSProtocol.procedures.medicationAdministration.medication.product.gtin</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.coding:GTIN">Medication.code.coding:GTIN</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.product.atc">EMSProtocol.procedures.medicationAdministration.medication.product.atc</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.coding:ATC">Medication.code.coding:ATC</a></td><td>0..*</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.product.freeText">EMSProtocol.procedures.medicationAdministration.medication.product.freeText</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.code.text">Medication.code.text</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.ingredient">EMSProtocol.procedures.medicationAdministration.medication.ingredient</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.ingredient.item[x]">Medication.ingredient.item[x]</a></td><td>1..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.galenicForm">EMSProtocol.procedures.medicationAdministration.medication.galenicForm</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.form">Medication.form</a></td><td>0..1</td><td>todo</td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.medicationAdministration.medication.packageSize">EMSProtocol.procedures.medicationAdministration.medication.packageSize</a></td><td>0..1</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-medication-definitions.html#Medication.amount">Medication.amount</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 4 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure-woundtreatment.html">CH EMS Procedure: Wound Treatment</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.woundTreatment">EMSProtocol.procedures.woundTreatment</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-woundtreatment-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 5 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure-airways.html">CH EMS Procedure: Airways</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.airway.intervention">EMSProtocol.procedures.airway.intervention</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-airways-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 6 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure-breathing.html">CH EMS Procedure: Breathing</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.breathing.intervention">EMSProtocol.procedures.breathing.intervention</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-breathing-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 7 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure.html">CH EMS Procedure (Base)</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.circulation.intervention">EMSProtocol.procedures.circulation.intervention</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 8 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure.html">CH EMS Procedure (Base)</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.disability.intervention">EMSProtocol.procedures.disability.intervention</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table><hr/><p><b>Group 9 </b>Mapping from <a href="StructureDefinition-logicalmodel-ems-protocol.html">EMS Protocol</a> to <a href="StructureDefinition-ch-ems-procedure.html">CH EMS Procedure (Base)</a></p><table class="grid"><tr><td><b>Source Code</b></td><td><b>Card.</b></td><td><b>Type</b></td><td><b>Relationship</b></td><td><b>Target Code</b></td><td><b>Card.</b></td><td><b>Type</b></td></tr><tr><td><a href="StructureDefinition-logicalmodel-ems-protocol.html#EMSProtocol.procedures.exposure.intervention">EMSProtocol.procedures.exposure.intervention</a></td><td>0..*</td><td>todo</td><td><a href="http://hl7.org/fhir/R5/codesystem-concept-map-relationship.html#equivalent" title="equivalent">is equivalent to</a></td><td><a href="StructureDefinition-ch-ems-procedure-definitions.html#Procedure.code">Procedure.code</a></td><td>0..1</td><td>todo</td></tr></table></div>
"""
// <<< conceptmap-narrative-hotfix

* group[0].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" // ?codesystem
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-composition" // ?codesystem
* group[=].element[0].code = #EMSProtocol.procedures
* group[=].element[=].target.code = #Composition.section:procedures
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-medicationadministration"
* group[=].element[0].code = #EMSProtocol.procedures.medicationAdministration.medication
* group[=].element[=].target.code = #MedicationAdministration.medication[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.dose
* group[=].element[=].target.code = #MedicationAdministration.dosage.dose
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.timing.time
* group[=].element[=].target.code = #MedicationAdministration.effective[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.timing.period
* group[=].element[=].target.code = #MedicationAdministration.effective[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.routeOfAdministration
* group[=].element[=].target.code = #MedicationAdministration.dosage.route
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.methodOfAdministration
* group[=].element[=].target.code = #MedicationAdministration.dosage.method
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.reason
* group[=].element[=].target.code = #MedicationAdministration.reasonCode.text
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol" 
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-medication" 
* group[=].element[0].code = #EMSProtocol.procedures.medicationAdministration.medication.product.gtin
* group[=].element[=].target.code = #Medication.code.coding:GTIN
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.medication.product.atc
* group[=].element[=].target.code = #Medication.code.coding:ATC
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.medication.product.freeText
* group[=].element[=].target.code = #Medication.code.text
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.medication.ingredient
* group[=].element[=].target.code = #Medication.ingredient.item[x]
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.medication.galenicForm
* group[=].element[=].target.code = #Medication.form
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #EMSProtocol.procedures.medicationAdministration.medication.packageSize
* group[=].element[=].target.code = #Medication.amount
* group[=].element[=].target.equivalence = #equivalent

* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure-woundtreatment"
* group[=].element[0].code = #EMSProtocol.procedures.woundTreatment
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent

// A
* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure-airways"
* group[=].element[0].code = #EMSProtocol.procedures.airway.intervention
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent

// B
* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure-breathing"
* group[=].element[0].code = #EMSProtocol.procedures.breathing.intervention
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent

// C
* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure"
* group[=].element[0].code = #EMSProtocol.procedures.circulation.intervention
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent

// D
* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure"
* group[=].element[0].code = #EMSProtocol.procedures.disability.intervention
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent

// E
* group[+].source = "http://fhir.ch/ig/ch-ems/StructureDefinition/logicalmodel-ems-protocol"
* group[=].target = "http://fhir.ch/ig/ch-ems/StructureDefinition/ch-ems-procedure"
* group[=].element[0].code = #EMSProtocol.procedures.exposure.intervention
* group[=].element[=].target.code = #Procedure.code
* group[=].element[=].target.equivalence = #equivalent
