// External code systems
Alias: $loinc =                             http://loinc.org
Alias: $sct =                               http://snomed.info/sct
Alias: $icd-10-gm =                         http://fhir.de/CodeSystem/dimdi/icd-10-gm
Alias: $ucum =                              http://unitsofmeasure.org 
Alias: $edqm =                              urn:oid:0.4.0.127.0.16.1.1.2.1

// HL7 code systems
Alias: $v3-ActCode =                        http://terminology.hl7.org/CodeSystem/v3-ActCode
Alias: $v2-0203 =                           http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $v3-RoleCode =                       http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $observation-category =              http://terminology.hl7.org/CodeSystem/observation-category
Alias: $data-absent-reason =                http://terminology.hl7.org/CodeSystem/data-absent-reason
Alias: $allergyintolerance-clinical =       http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical

// Structure definitions
Alias: $shareablevalueset =                 http://hl7.org/fhir/StructureDefinition/shareablevalueset
Alias: $iso21090-ADXP-houseNumber =         http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber
Alias: $ch-ext-ech-10-linetype =            http://fhir.ch/ig/ch-core/StructureDefinition/ch-ext-ech-10-linetype
Alias: $ch-core-gln-identifier =            http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-gln-identifier
Alias: $itemWeight =                        http://hl7.org/fhir/StructureDefinition/itemWeight
Alias: $imposeProfile =                     http://hl7.org/fhir/StructureDefinition/structuredefinition-imposeProfile

// CH EMS terminology
Alias: $IVR-CS =                            http://fhir.ch/ig/ch-ems/CodeSystem/IVR
Alias: $IVR-VS-findingsAirway =             http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-findingsAirway
Alias: $IVR-VS-event =                      http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-event
Alias: $IVR-VS-vigilanzAvpu =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-vigilanzAvpu
Alias: $IVR-VS-result =                     http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-result
Alias: $IVR-VS-diagType =                   http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-diagType
Alias: $IVR-VS-missionTimeRole =            http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-missionTimeRole
Alias: $IVR-VS-NACA =                       http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-NACA
Alias: $IVR-VS-hospitalPriority =           http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-hospitalPriority
Alias: $IVR-VS-teamRole =                   http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-teamRole
Alias: $IVR-VS-preTreatType =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-preTreatType
Alias: $IVR-VS-preTreatment =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-preTreatment
Alias: $IVR-VS-personRole =                 http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-personRole
Alias: $IVR-VS-procAirType =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-procAirType
Alias: $IVR-VS-ventilation =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-ventilation
Alias: $IVR-VS-respirationObservation =     http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-respirationObservation
Alias: $IVR-VS-gcs-augenoeffnung =          http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-gcs-augenoeffnung
Alias: $IVR-VS-gcsMotoric =                 http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-gcsMotoric
Alias: $IVR-VS-gcsVerbal =                  http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-gcsVerbal
Alias: $IVR-VS-coldExposure =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-coldExposure
Alias: $IVR-VS-heatExposure =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-heatExposure
Alias: $IVR-VS-pulesResult =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-pulesResult
Alias: $IVR-VS-pulseMethod =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-pulseMethod
Alias: $IVR-VS-pressureMethod =             http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-pressureMethod
Alias: $IVR-VS-eyeForm =                    http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-eyeForm
Alias: $IVR-VS-size =                       http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-size
Alias: $IVR-VS-symptom =                    http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-symptom
Alias: $IVR-VS-InfectPersPrecaution =       http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-InfectPersPrecaution
Alias: $IVR-VS-actRecovAid =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-actRecovAid
Alias: $IVR-VS-bedding =                    http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-bedding
Alias: $IVR-VS-formation =                  http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-formation
Alias: $IVR-VS-urgency =                    http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-urgency
Alias: $IVR-VS-urgency-adequate =           http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-urgency-adequate
Alias: $IVR-VS-valType =                    http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-valType
Alias: $IVR-VS-transReason =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-transReason
Alias: $IVR-VS-woundTreat =                 http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-woundTreat
Alias: $IVR-VS-missionType =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-missionType
Alias: $IVR-VS-emergDoctSystem =            http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-emergDoctSystem
Alias: $IVR-VS-idMedium =                   http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-idMedium
Alias: $IVR-VS-idSource =                   http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-idSource
Alias: $IVR-VS-intensity =                  http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-intensity
Alias: $IVR-VS-locationType =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-locationType
Alias: $IVR-VS-deathManner =                http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-deathManner
Alias: $IVR-VS-ambulanceType =              http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-ambulanceType
Alias: $IVR-VS-transDisinfection =          http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-transDisinfection
Alias: $IVR-VS-violenceForm =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-violenceForm
Alias: $IVR-VS-violenceResult =             http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-violenceResult
Alias: $IVR-VS-offender =                   http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-offender
Alias: $IVR-VS-actRespiOwner =              http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-actRespiOwner
Alias: $IVR-VS-yesNoUnknown =               http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-yesNoUnknown
Alias: $IVR-VS-laterality =                 http://fhir.ch/ig/ch-ems/ValueSet/IVR-VS-laterality
