Instance: 1-Einsatzprotokoll
InstanceOf: CHEmsDocument
Title: "1 Einsatzprotokoll"
Description: "Example for CH EMS Document - Use case 1 at patient handover (EPR conform)"
Usage: #example
* meta.lastUpdated = "2020-04-24T07:53:22.889+00:00"
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:658ab5ea-1f63-11e6-b6ba-3e1d05defe78"
* type = #document
* timestamp = "2016-12-10T13:05:00.000+01:00"
* entry[0].fullUrl = "http://test.fhir.ch/r4/Composition/1-Einsatzprotokoll-Composition"
* entry[=].resource = 1-Einsatzprotokoll-Composition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Encounter/1-Einsatz"
* entry[=].resource = 1-Einsatz
* entry[+].fullUrl = "http://test.fhir.ch/r4/Patient/1-ThomasMueller"
* entry[=].resource = 1-ThomasMueller
* entry[+].fullUrl = "http://test.fhir.ch/r4/Coverage/1-CoverageThomasMueller"
* entry[=].resource = 1-CoverageThomasMueller
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-InformationRecipientSpitalarzt"
* entry[=].resource = 1-InformationRecipientSpitalarzt
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-InformationRecipientUSZ"
* entry[=].resource = 1-InformationRecipientUSZ
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-SaniPetraMuster"
* entry[=].resource = 1-SaniPetraMuster
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/1-SaniPetraMuster-PR"
* entry[=].resource = 1-SaniPetraMuster-PR
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-NotarztPierreUrgentiste"
* entry[=].resource = 1-NotarztPierreUrgentiste
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/1-NotarztPierreUrgentiste-PR"
* entry[=].resource = 1-NotarztPierreUrgentiste-PR
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-TeamMemberPetraMuster"
* entry[=].resource = 1-TeamMemberPetraMuster
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-TeamMemberHansTransportsanitaeter"
* entry[=].resource = 1-TeamMemberHansTransportsanitaeter
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-TeamMemberPierreUrgentiste"
* entry[=].resource = 1-TeamMemberPierreUrgentiste
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-Rettungsdienst"
* entry[=].resource = 1-Rettungsdienst
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-TeamRettungsdienst"
* entry[=].resource = 1-TeamRettungsdienst
* entry[+].fullUrl = "http://test.fhir.ch/r4/ServiceRequest/1-AufbietendeOrganisation"
* entry[=].resource = 1-AufbietendeOrganisation
* entry[+].fullUrl = "http://test.fhir.ch/r4/Location/1-Einsatzort"
* entry[=].resource = 1-Einsatzort
* entry[+].fullUrl = "http://test.fhir.ch/r4/Location/1-Zielort"
* entry[=].resource = 1-Zielort
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Alarm"
* entry[=].resource = 1-Alarm
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Disposition"
* entry[=].resource = 1-Disposition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Rollout"
* entry[=].resource = 1-Rollout
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-ArrivalOnScene"
* entry[=].resource = 1-ArrivalOnScene
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-ArrivalPatient"
* entry[=].resource = 1-ArrivalPatient
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-DepartureFromScene"
* entry[=].resource = 1-DepartureFromScene
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-ArrivalAtTarget"
* entry[=].resource = 1-ArrivalAtTarget
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Anamnese"
* entry[=].resource = 1-Anamnese
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Symptome"
* entry[=].resource = 1-Symptome
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-GCSBefund"
* entry[=].resource = 1-GCSBefund
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Diagnose"
* entry[=].resource = 1-Diagnose
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-ZustandUebergabe"
* entry[=].resource = 1-ZustandUebergabe
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-NACAUebergabe"
* entry[=].resource = 1-NACAUebergabe
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-GCSUebergabe"
* entry[=].resource = 1-GCSUebergabe
* entry[+].fullUrl = "http://test.fhir.ch/r4/Location/1-Rettungswagen"
* entry[=].resource = 1-Rettungswagen
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/1-Blutdruck"
* entry[=].resource = 1-Blutdruck
* entry[+].fullUrl = "http://test.fhir.ch/r4/MedicationAdministration/1-Infusion"
* entry[=].resource = 1-Infusion
* entry[+].fullUrl = "http://test.fhir.ch/r4/MedicationAdministration/1-Spray"
* entry[=].resource = 1-Spray
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/1-Baumpollen"
* entry[=].resource = 1-Baumpollen
* entry[+].fullUrl = "http://test.fhir.ch/r4/AllergyIntolerance/1-Medikamente"
* entry[=].resource = 1-Medikamente

/* validation test case
* entry[+].fullUrl = "http://test.fhir.ch/r4/MedicationAdministration/MedAdminFentanyl"
* entry[=].resource = MedAdminFentanyl
* entry[+].fullUrl = "http://test.fhir.ch/r4/Procedure/ProcedureAirwaysIntubation"
* entry[=].resource = ProcedureAirwaysIntubation
*/
