Instance: 2b-Einsatzprotokoll
InstanceOf: CHEmsDocument
Title: "2b Einsatzprotokoll"
Description: "Example for CH EMS Document - Use case 2 at operational readiness (not EPR conform because of unknown patient)"
Usage: #example
* meta.lastUpdated = "2020-04-24T15:53:22.889+00:00"
* identifier.system = "urn:ietf:rfc:3986"
* identifier.value = "urn:uuid:b4044742-ab2c-49f6-8151-0e2be5d3f923"
* type = #document
* timestamp = "2016-12-10T13:40:00.000+01:00"
* entry[0].fullUrl = "http://test.fhir.ch/r4/Composition/2b-Einsatzprotokoll-Composition"
* entry[=].resource = 2b-Einsatzprotokoll-Composition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Encounter/2-Einsatz"
* entry[=].resource = 2-Einsatz
* entry[+].fullUrl = "http://test.fhir.ch/r4/Patient/2-PatientUnbekannt"
* entry[=].resource = 2-PatientUnbekannt
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-InformationRecipientSpitalarzt"
* entry[=].resource = 1-InformationRecipientSpitalarzt
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-InformationRecipientUSZ"
* entry[=].resource = 1-InformationRecipientUSZ
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-SaniPetraMuster"
* entry[=].resource = 1-SaniPetraMuster
* entry[+].fullUrl = "http://test.fhir.ch/r4/PractitionerRole/1-SaniPetraMuster-PR"
* entry[=].resource = 1-SaniPetraMuster-PR
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-TeamMemberPetraMuster"
* entry[=].resource = 1-TeamMemberPetraMuster
* entry[+].fullUrl = "http://test.fhir.ch/r4/Practitioner/1-TeamMemberHansTransportsanitaeter"
* entry[=].resource = 1-TeamMemberHansTransportsanitaeter
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-Rettungsdienst"
* entry[=].resource = 1-Rettungsdienst
* entry[+].fullUrl = "http://test.fhir.ch/r4/Organization/1-TeamRettungsdienst"
* entry[=].resource = 1-TeamRettungsdienst
* entry[+].fullUrl = "http://test.fhir.ch/r4/ServiceRequest/2-AufbietendeOrganisation"
* entry[=].resource = 2-AufbietendeOrganisation
* entry[+].fullUrl = "http://test.fhir.ch/r4/Location/2-Einsatzort"
* entry[=].resource = 2-Einsatzort
* entry[+].fullUrl = "http://test.fhir.ch/r4/Location/1-Zielort"
* entry[=].resource = 1-Zielort
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-Alarm"
* entry[=].resource = 2-Alarm
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-Disposition"
* entry[=].resource = 2-Disposition
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-Rollout"
* entry[=].resource = 2-Rollout
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-ArrivalOnScene"
* entry[=].resource = 2-ArrivalOnScene
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-ArrivalPatient"
* entry[=].resource = 2-ArrivalPatient
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-DepartureFromScene"
* entry[=].resource = 2-DepartureFromScene
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-ArrivalAtTarget"
* entry[=].resource = 2-ArrivalAtTarget
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2b-DepartureFromTarget"
* entry[=].resource = 2b-DepartureFromTarget
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2b-OperationalReadiness"
* entry[=].resource = 2b-OperationalReadiness
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-AirwaysBefund"
* entry[=].resource = 2-AirwaysBefund
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-GCSBefund"
* entry[=].resource = 2-GCSBefund
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-AVPUBefund"
* entry[=].resource = 2-AVPUBefund
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-Diagnose"
* entry[=].resource = 2-Diagnose
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-ZustandUebergabe"
* entry[=].resource = 2-ZustandUebergabe
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-NACAUebergabe"
* entry[=].resource = 2-NACAUebergabe
* entry[+].fullUrl = "http://test.fhir.ch/r4/Observation/2-GCSUebergabe"
* entry[=].resource = 2-GCSUebergabe