#!/usr/bin/env python3
"""
Fix the ConceptMap ("Model Map") narratives so their hyperlinks resolve.

Why this exists (issue #42)
---------------------------
The Model Maps are FHIR ConceptMaps whose source/target "codes" are element ids of
StructureDefinitions (valid implicit code systems per FHIR R4 spec section 4.8.15). The
IG Publisher auto-generates a narrative for each ConceptMap whose *target* links point at
"StructureDefinition-<profile>.html#<elementId>". But the profile pages anchor elements as
"k-<path>.<n>" (slices flattened to numbers), so those links 404 -> hundreds of
HTML_LINK_CHECK_FAILED / "Hyperlink ... does not resolve" errors.

The exact element-id anchors (incl. slice names like "Composition.section:administrative")
DO exist on the companion "...-definitions.html" page. So this script:
  1. reads each ConceptMap's generated narrative from a completed build (output/),
  2. strips the "Generated Narrative" header marker (so an #additional narrative is not
     flagged as looking generated),
  3. rewrites ch-ems profile target links "<profile>.html#<frag>" ->
     "<profile>-definitions.html#<frag>" (source/logical-model links already resolve),
  4. injects the result into the FSH ConceptMap as text.status = #additional, which the
     IG Publisher preserves instead of regenerating.

The injected block is delimited by sentinels and the script is idempotent, so re-running
after editing a map refreshes the narrative cleanly.

Usage (run AFTER a build, then rebuild):
    python3 scripts/fix-conceptmap-narratives.py            # all maps
    python3 scripts/fix-conceptmap-narratives.py EmsPatient2Fhir   # one map (by Instance name)
    java -Xms3550m -Xmx3550m -jar publisher.jar -ig ig.ini

See https://github.com/hl7ch/ch-ems/issues/42
"""
import json, re, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAPS = os.path.join(ROOT, "input", "fsh", "maps")
OUT  = os.path.join(ROOT, "output")

BEGIN = "// >>> conceptmap-narrative-hotfix (generated by scripts/fix-conceptmap-narratives.py, see #42)"
END   = "// <<< conceptmap-narrative-hotfix"


def fix_div(div):
    div = re.sub(r'<p class="res-header-id"><b>Generated Narrative:.*?</b></p>', "", div, flags=re.S)
    # idempotent: normalise any prior rewrite, then point ch-ems profile fragment links
    # at the -definitions page (which has the element-id anchors).
    div = div.replace("-definitions.html#", ".html#")
    div = re.sub(r"(StructureDefinition-ch-ems-[a-z0-9-]+?)\.html#", r"\1-definitions.html#", div)
    return div.strip()


def block(div):
    return f'{BEGIN}\n* text.status = #additional\n* text.div = """\n{div}\n"""\n{END}\n'


def strip_existing(src):
    # remove a previous sentinel block, plus any hand-written hotfix comment / text block
    src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", src, flags=re.S)
    src = re.sub(r"(?m)^//[^\n]*HOTFIX[^\n]*\n(?:^//[^\n]*\n)*", "", src)
    src = re.sub(r'(?m)^\* text\.status\s*=\s*#\w+\s*\n', "", src)
    src = re.sub(r'\* text\.div = """.*?"""\n', "", src, flags=re.S)
    return src


def process(fsh, only):
    src = open(fsh).read()
    m = re.search(r"^Instance:\s*(\S+)", src, re.M)
    if not m:
        return None
    name = m.group(1)
    if only and name != only:
        return None
    j = os.path.join(OUT, f"ConceptMap-{name}.json")
    if not os.path.exists(j):
        print(f"  skip {name}: no {os.path.relpath(j, ROOT)} (run a build first)")
        return None
    div = json.load(open(j)).get("text", {}).get("div")
    if not div:
        print(f"  skip {name}: no narrative in build output")
        return None
    src = strip_existing(src)
    blk = block(fix_div(div))
    gm = re.search(r"(?m)^\* group", src)
    if gm:
        src = src[:gm.start()] + blk + "\n" + src[gm.start():]
    else:
        src = src.rstrip() + "\n\n" + blk
    open(fsh, "w").write(src)
    print(f"  fixed {name}")
    return name


def main():
    only = sys.argv[1] if len(sys.argv) > 1 else None
    n = 0
    for fsh in sorted(glob.glob(os.path.join(MAPS, "*.fsh"))):
        if process(fsh, only):
            n += 1
    print(f"done: {n} ConceptMap narrative(s) fixed")


if __name__ == "__main__":
    main()
