@host = http://test.ahdis.ch/fhir


###
PUT {{host}}/Patient/1-PeterMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/1-PeterMuster.xml


###
PUT {{host}}/Practitioner/1-BetreuerHansBeispiel HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-BetreuerHansBeispiel.xml

###
PUT {{host}}/Practitioner/1-BetreuerPetraMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-BetreuerPetraMuster.xml

###
PUT {{host}}/Practitioner/1-InformationRecipientSpezialarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-InformationRecipientSpezialarzt.xml

###
PUT {{host}}/Practitioner/1-NotarztHansNotarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-NotarztHansNotarzt.xml

###
PUT {{host}}/Practitioner/1-NotarztHansNotarztHansNotarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-NotarztHansNotarztHansNotarzt.xml

###
PUT {{host}}/Practitioner/1-SaniPetraMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/1-SaniPetraMuster.xml


###
PUT {{host}}/PractitionerRole/1-NotarztHansNotarzt HTTP/1.1
Content-Type: application/fhir+xml

< ./practitionerrole/1-NotarztHansNotarzt.xml

###
PUT {{host}}/PractitionerRole/1-SaniPetraMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./practitionerrole/1-SaniPetraMuster.xml


###
PUT {{host}}/RelatedPerson/1-Ehefrau HTTP/1.1
Content-Type: application/fhir+xml

< ./relatedperson/1-Ehefrau.xml


###
PUT {{host}}/Coverage/1-CoveragePeterMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./coverage/1-CoveragePeterMuster.xml


###
PUT {{host}}/Organization/1-InformationRecipientUSZ HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/1-InformationRecipientUSZ.xml

###
PUT {{host}}/Organization/1-Rettungsdienst HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/1-Rettungsdienst.xml

###
PUT {{host}}/Organization/1-TeamRettungsdienst HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/1-TeamRettungsdienst.xml


###
PUT {{host}}/ServiceRequest/1-AufbietendeOrganisation HTTP/1.1
Content-Type: application/fhir+xml

< ./servicerequest/1-AufbietendeOrganisation.xml


###
PUT {{host}}/Location/1-Einsatzort HTTP/1.1
Content-Type: application/fhir+xml

< ./location/1-Einsatzort.xml

###
PUT {{host}}/Location/1-Zielort HTTP/1.1
Content-Type: application/fhir+xml

< ./location/1-Zielort.xml


###
PUT {{host}}/Observation/1-Alarm HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Alarm.xml

###
PUT {{host}}/Observation/1-Anamnese HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Anamnese.xml

###
PUT {{host}}/Observation/1-ArrivalAtTarget HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-ArrivalAtTarget.xml

###
PUT {{host}}/Observation/1-ArrivalOnScene HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-ArrivalOnScene.xml

###
PUT {{host}}/Observation/1-ArrivalPatient HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-ArrivalPatient.xml

###
PUT {{host}}/Observation/1-DepartureFromScene HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-DepartureFromScene.xml

###
PUT {{host}}/Observation/1-Diagnose HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Diagnose.xml

###
PUT {{host}}/Observation/1-Disposition HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Disposition.xml

###
PUT {{host}}/Observation/1-GCSBefund HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-GCSBefund.xml

###
PUT {{host}}/Observation/1-GCSUebergabe HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-GCSUebergabe.xml

###
PUT {{host}}/Observation/1-NACAUebergabe HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-NACAUebergabe.xml

###
PUT {{host}}/Observation/1-Rollout HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Rollout.xml

###
PUT {{host}}/Observation/1-Symptome HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-Symptome.xml

###
PUT {{host}}/Observation/1-ZustandUebergabe HTTP/1.1
Content-Type: application/fhir+xml

< ./observation/1-ZustandUebergabe.xml


###
PUT {{host}}/Encounter/1-Einsatz HTTP/1.1
Content-Type: application/fhir+xml

< ./encounter/1-Einsatz.xml




###
PUT {{host}}/Composition/1-Einsatzprotokoll HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/1-Einsatzprotokoll.xml


###
GET {{host}}/Composition/1-Einsatzprotokoll/$document HTTP/1.1
Content-Type: application/fhir+xml




###
GET {{host}}/Organization/1-InformationRecipientUSZ HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Organization/1-Rettungsdienst HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Organization/1-TeamRettungsdienst HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Location/1-Zielort HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Practitioner/1-InformationRecipientSpezialarzt HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Coverage/1-CoveragePeterMuster HTTP/1.1
Content-Type: application/fhir+xml

###
GET http://test.fhir.ch/r4/Patient/1-PeterMuster HTTP/1.1
Content-Type: application/fhir+xml